create category
AT-PHPIntership/selling-mobile pull request #23
Opened 2018-08-02 04:52 UTC by at-betruong

## Description
- Create new category
## Reference Requirements
- Task ID: TI-1

## Reference Isuees

## Migrations
YES

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-02 10:31 UTC, at-xinhnguyen commented on resources/views/pages/categories/create.blade.php
> +@extends('backend.master')
em move cái thư mục pages này vào bên trong backend đi. tại phần này thuộc backend. ít bữa mình sẽ có 1 folder frontend ngang hàng với `backend`

2018-08-03 01:44 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +                return redirect()->route('admin.categories.index')->with('message', __('category.admin.message.add'));
chỗ này em dùng flash hay hơn ấy
`Session::flash('message', 'This is a message!'); `
`Session::flash('alert-class', 'alert-danger'); ` or `Session::flash('alert-class', 'alert-success'); `

ở view
```
@if(Session::has('message'))
<p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
@endif
```
support bootstrap luôn

2018-08-03 01:49 UTC, at-xinhnguyen commented on routes/web.php
> +});
thêm space cho thẳng hàng luôn em

2018-08-03 01:57 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        } catch (Exception $ex) {
chỗ này 1 là em `use Exception` hay là dùng `\Exception`

2018-08-03 01:59 UTC, ghost requested changes
Please check my cmt

2018-08-03 02:39 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +        return view('backend.pages.categories.index', $data);
`categories.index` => `categories.create` em

2018-08-03 02:40 UTC, at-xinhnguyen commented on app/Http/Controllers/Admin/CategoryController.php
> +                return redirect()->route('admin.categories.create');
categories.create => categories.index

2018-08-03 02:41 UTC, at-xinhnguyen commented on routes/web.php
> +		});
em chỉnh lại cho đúng convention code nhé.

2018-08-03 02:42 UTC, at-betruong commented on app/Http/Controllers/Admin/CategoryController.php
> +                return redirect()->route('admin.categories.create');
dạ, do e tính thông báo bên trang list

2018-08-03 03:28 UTC, ghost approved these changes
LGTM

2018-08-03 03:28 UTC, merged