Register user
AT-PHPIntership/selling-mobile pull request #46
Opened 2018-08-28 00:54 UTC by at-betruong

## Description
A few sentences describing the overall goals of the pull request's commits.
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
YES | NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-28 02:09 UTC, at-xinhnguyen commented on app/Http/Requests/User/ApiFormRequest.php
> +    }
k cần hàm này đâu em. mỗi cái request khi extend thằng này thì đã có hàm rules rồi

2018-08-28 02:11 UTC, at-xinhnguyen commented on public/user/js/register.js
> +          window.location.href = 'http://' + window.location.hostname;
em dùng biến app_url trong .env và truyền qua javascript đi (window.base_url).

2018-08-28 02:12 UTC, at-xinhnguyen commented on public/user/js/register.js
> +          console.log(value);
bỏ debug đi em

2018-08-28 02:15 UTC, at-xinhnguyen commented on app/Http/Controllers/Api/User/LoginController.php
> +            $input = $request->except('password');
ở dưới em đã ghi đè giá trị cái password rồi thì cần gì except password em

2018-08-28 02:18 UTC, at-xinhnguyen commented on resources/views/public/pages/register.blade.php
> +  <center><h3>Register Account</h3></center>
trans text này đi em

2018-08-28 02:18 UTC, at-xinhnguyen commented on resources/views/public/pages/register.blade.php
> +      <p class="contact"><label for="phonenumber">Your Phone</label></p>
trans text hết đi em

2018-08-28 02:19 UTC, ghost requested changes
Pls check my cmt

2018-08-28 03:16 UTC, at-betruong commented on app/Http/Controllers/Api/User/LoginController.php
> +            $input = $request->except('password');
cái này e lấy thuộc tính 'password' trong $request ra để bcrypt() nó add vô DB cho dong phía dưới đó a

2018-08-29 04:57 UTC, ghost approved these changes
LGTM

2018-08-29 04:58 UTC, merged